import * as dateFns from "date-fns";
import { DataType, IData, OperationType } from "../types";
import { createDataFromRawValue, getRawValueFromData } from "../utils";
import { Context, OperationListItem } from "../execution/types";

const TDate: DataType = {
  kind: "instance",
  className: "Date",
  constructorArgs: [],
};
const TString: DataType = { kind: "string" };
const TNumber: DataType = { kind: "number" };
const TBool: DataType = { kind: "boolean" };
const TUnknown: DataType = { kind: "unknown" };

const TDateArg: DataType = { kind: "union", types: [TDate, TNumber, TString] };

const TDateArgsArr: DataType = { kind: "array", elementType: TDateArg };

const TDuration: DataType = {
  kind: "object",
  properties: [
    { key: "years", value: TNumber },
    { key: "months", value: TNumber },
    { key: "weeks", value: TNumber },
    { key: "days", value: TNumber },
    { key: "hours", value: TNumber },
    { key: "minutes", value: TNumber },
    { key: "seconds", value: TNumber },
  ],
};

const TInterval: DataType = {
  kind: "object",
  properties: [
    { key: "start", value: TDateArg },
    { key: "end", value: TDateArg },
  ],
  required: ["start", "end"],
};

const TDateValues: DataType = {
  kind: "object",
  properties: [
    { key: "year", value: TNumber },
    { key: "month", value: TNumber },
    { key: "date", value: TNumber },
    { key: "hours", value: TNumber },
    { key: "minutes", value: TNumber },
    { key: "seconds", value: TNumber },
    { key: "milliseconds", value: TNumber },
  ],
};

const TOptions: OperationType["parameters"][number] = {
  type: { kind: "object", properties: [] },
  isOptional: true,
};
function createOp(
  name: string,
  params: (DataType | OperationType["parameters"][number])[],
  resultType?: DataType
): OperationListItem {
  return {
    name,
    parameters: params.map((p) => ("type" in p ? p : { type: p })),
    source: { name: "dateFns" },
    handler: (_context: Context, data: IData, ...args: IData[]) => {
      const rawFirst = getRawValueFromData(data, _context);
      const rawArgs = args.map((a) => getRawValueFromData(a, _context));
      const fn = (
        dateFns as unknown as Record<string, (...a: unknown[]) => unknown>
      )[name];
      if (!fn) throw new Error(`date-fns function "${name}" not found`);
      const result = fn(rawFirst, ...rawArgs);
      return createDataFromRawValue(result, {
        ..._context,
        expectedType: resultType,
      });
    },
  };
}

export const operations: OperationListItem[] = [
  createOp("add", [TDateArg, TDuration, TOptions], TDate),
  createOp("addBusinessDays", [TDateArg, TNumber, TOptions], TDate),
  createOp("addDays", [TDateArg, TNumber, TOptions], TDate),
  createOp("addHours", [TDateArg, TNumber, TOptions], TDate),
  createOp("addISOWeekYears", [TDateArg, TNumber, TOptions], TDate),
  createOp("addMilliseconds", [TDateArg, TNumber, TOptions], TDate),
  createOp("addMinutes", [TDateArg, TNumber, TOptions], TDate),
  createOp("addMonths", [TDateArg, TNumber, TOptions], TDate),
  createOp("addQuarters", [TDateArg, TNumber, TOptions], TDate),
  createOp("addSeconds", [TDateArg, TNumber, TOptions], TDate),
  createOp("addWeeks", [TDateArg, TNumber, TOptions], TDate),
  createOp("addYears", [TDateArg, TNumber, TOptions], TDate),
  createOp("areIntervalsOverlapping", [TInterval, TInterval, TOptions], TBool),
  createOp("clamp", [TDateArg, TInterval, TOptions], TDate),
  createOp("closestIndexTo", [TDateArg, TDateArgsArr], TNumber),
  createOp("closestTo", [TDateArg, TDateArgsArr, TOptions], TDate),
  createOp("compareAsc", [TDateArg, TDateArg], TNumber),
  createOp("compareDesc", [TDateArg, TDateArg], TNumber),
  createOp(
    "constructFrom",
    [{ type: TDateArg, isOptional: true }, TDateArg],
    TDate
  ),
  createOp("constructNow", [{ type: TDateArg, isOptional: true }], TDate),
  createOp("daysToWeeks", [TNumber], TNumber),
  createOp("differenceInBusinessDays", [TDateArg, TDateArg, TOptions], TNumber),
  createOp("differenceInCalendarDays", [TDateArg, TDateArg, TOptions], TNumber),
  createOp(
    "differenceInCalendarISOWeeks",
    [TDateArg, TDateArg, TOptions],
    TNumber
  ),
  createOp(
    "differenceInCalendarISOWeekYears",
    [TDateArg, TDateArg, TOptions],
    TNumber
  ),
  createOp(
    "differenceInCalendarMonths",
    [TDateArg, TDateArg, TOptions],
    TNumber
  ),
  createOp(
    "differenceInCalendarQuarters",
    [TDateArg, TDateArg, TOptions],
    TNumber
  ),
  createOp(
    "differenceInCalendarWeeks",
    [TDateArg, TDateArg, TOptions],
    TNumber
  ),
  createOp(
    "differenceInCalendarYears",
    [TDateArg, TDateArg, TOptions],
    TNumber
  ),
  createOp("differenceInDays", [TDateArg, TDateArg, TOptions], TNumber),
  createOp("differenceInHours", [TDateArg, TDateArg, TOptions], TNumber),
  createOp("differenceInISOWeekYears", [TDateArg, TDateArg, TOptions], TNumber),
  createOp("differenceInMilliseconds", [TDateArg, TDateArg], TNumber),
  createOp("differenceInMinutes", [TDateArg, TDateArg, TOptions], TNumber),
  createOp("differenceInMonths", [TDateArg, TDateArg, TOptions], TNumber),
  createOp("differenceInQuarters", [TDateArg, TDateArg, TOptions], TNumber),
  createOp("differenceInSeconds", [TDateArg, TDateArg, TOptions], TNumber),
  createOp("differenceInWeeks", [TDateArg, TDateArg, TOptions], TNumber),
  createOp("differenceInYears", [TDateArg, TDateArg, TOptions], TNumber),
  createOp("eachDayOfInterval", [TInterval, TOptions], TInterval),
  createOp("eachHourOfInterval", [TInterval, TOptions], TInterval),
  createOp("eachMinuteOfInterval", [TInterval, TOptions], TInterval),
  createOp("eachMonthOfInterval", [TInterval, TOptions], TInterval),
  createOp("eachQuarterOfInterval", [TInterval, TOptions], TInterval),
  createOp("eachWeekendOfInterval", [TInterval, TOptions], TInterval),
  createOp("eachWeekendOfMonth", [TDateArg, TOptions], TDate),
  createOp("eachWeekendOfYear", [TDateArg, TOptions], TDate),
  createOp("eachWeekOfInterval", [TInterval, TOptions], TInterval),
  createOp("eachYearOfInterval", [TInterval, TOptions], TInterval),
  createOp("endOfDay", [TDateArg, TOptions], TDate),
  createOp("endOfDecade", [TDateArg, TOptions], TDate),
  createOp("endOfHour", [TDateArg, TOptions], TDate),
  createOp("endOfISOWeek", [TDateArg, TOptions], TDate),
  createOp("endOfISOWeekYear", [TDateArg, TOptions], TDate),
  createOp("endOfMinute", [TDateArg, TOptions], TDate),
  createOp("endOfMonth", [TDateArg, TOptions], TDate),
  createOp("endOfQuarter", [TDateArg, TOptions], TDate),
  createOp("endOfSecond", [TDateArg, TOptions], TDate),
  createOp("endOfToday", [TOptions], TDate),
  createOp("endOfTomorrow", [TOptions], TDate),
  createOp("endOfWeek", [TDateArg, TOptions], TDate),
  createOp("endOfYear", [TDateArg, TOptions], TDate),
  createOp("endOfYesterday", [TOptions], TDate),
  createOp("format", [TDateArg, TString, TOptions], TString),
  createOp("formatDistance", [TDateArg, TDateArg, TOptions], TString),
  createOp("formatDistanceStrict", [TDateArg, TDateArg, TOptions], TString),
  createOp("formatDistanceToNow", [TDateArg, TOptions], TString),
  createOp("formatDistanceToNowStrict", [TDateArg, TOptions], TString),
  createOp("formatDuration", [TDuration, TOptions], TString),
  createOp("formatISO", [TDateArg, TOptions], TString),
  createOp("formatISO9075", [TDateArg, TOptions], TString),
  createOp("formatISODuration", [TDuration], TString),
  createOp("formatRelative", [TDateArg, TDateArg, TOptions], TString),
  createOp("formatRFC3339", [TDateArg, TOptions], TString),
  createOp("formatRFC7231", [TDateArg], TString),
  createOp("fromUnixTime", [TNumber, TOptions], TDate),
  createOp("getDate", [TDateArg, TOptions], TNumber),
  createOp("getDay", [TDateArg, TOptions], TNumber),
  createOp("getDayOfYear", [TDateArg, TOptions], TNumber),
  createOp("getDaysInMonth", [TDateArg, TOptions], TNumber),
  createOp("getDaysInYear", [TDateArg, TOptions], TNumber),
  createOp("getDecade", [TDateArg, TOptions], TNumber),
  createOp("getHours", [TDateArg, TOptions], TNumber),
  createOp("getISODay", [TDateArg, TOptions], TNumber),
  createOp("getISOWeek", [TDateArg, TOptions], TNumber),
  createOp("getISOWeeksInYear", [TDateArg, TOptions], TNumber),
  createOp("getISOWeekYear", [TDateArg, TOptions], TNumber),
  createOp("getMilliseconds", [TDateArg], TNumber),
  createOp("getMinutes", [TDateArg, TOptions], TNumber),
  createOp("getMonth", [TDateArg, TOptions], TNumber),
  createOp("getOverlappingDaysInIntervals", [TInterval, TInterval], TNumber),
  createOp("getQuarter", [TDateArg, TOptions], TNumber),
  createOp("getSeconds", [TDateArg], TNumber),
  createOp("getTime", [TDateArg], TNumber),
  createOp("getUnixTime", [TDateArg], TNumber),
  createOp("getWeek", [TDateArg, TOptions], TNumber),
  createOp("getWeekOfMonth", [TDateArg, TOptions], TNumber),
  createOp("getWeeksInMonth", [TDateArg, TOptions], TNumber),
  createOp("getWeekYear", [TDateArg, TOptions], TNumber),
  createOp("getYear", [TDateArg, TOptions], TNumber),
  createOp("hoursToMilliseconds", [TNumber], TNumber),
  createOp("hoursToMinutes", [TNumber], TNumber),
  createOp("hoursToSeconds", [TNumber], TNumber),
  createOp("interval", [TDateArg, TDateArg, TOptions], TInterval),
  createOp("intervalToDuration", [TInterval, TOptions], TDuration),
  createOp("intlFormat", [TDateArg, TOptions, TOptions], TString),
  createOp("intlFormatDistance", [TDateArg, TDateArg, TOptions], TString),
  createOp("isAfter", [TDateArg, TDateArg], TBool),
  createOp("isBefore", [TDateArg, TDateArg], TBool),
  createOp("isDate", [TUnknown], TBool),
  createOp("isEqual", [TDateArg, TDateArg], TBool),
  createOp("isExists", [TNumber, TNumber, TNumber], TBool),
  createOp("isFirstDayOfMonth", [TDateArg, TOptions], TBool),
  createOp("isFriday", [TDateArg, TOptions], TBool),
  createOp("isFuture", [TDateArg], TBool),
  createOp("isLastDayOfMonth", [TDateArg, TOptions], TBool),
  createOp("isLeapYear", [TDateArg, TOptions], TBool),
  createOp("isMatch", [TString, TString, TOptions], TBool),
  createOp("isMonday", [TDateArg, TOptions], TBool),
  createOp("isPast", [TDateArg], TBool),
  createOp("isSameDay", [TDateArg, TDateArg, TOptions], TBool),
  createOp("isSameHour", [TDateArg, TDateArg, TOptions], TBool),
  createOp("isSameISOWeek", [TDateArg, TDateArg, TOptions], TBool),
  createOp("isSameISOWeekYear", [TDateArg, TDateArg, TOptions], TBool),
  createOp("isSameMinute", [TDateArg, TDateArg], TBool),
  createOp("isSameMonth", [TDateArg, TDateArg, TOptions], TBool),
  createOp("isSameQuarter", [TDateArg, TDateArg, TOptions], TBool),
  createOp("isSameSecond", [TDateArg, TDateArg], TBool),
  createOp("isSameWeek", [TDateArg, TDateArg, TOptions], TBool),
  createOp("isSameYear", [TDateArg, TDateArg, TOptions], TBool),
  createOp("isSaturday", [TDateArg, TOptions], TBool),
  createOp("isSunday", [TDateArg, TOptions], TBool),
  createOp("isThisHour", [TDateArg, TOptions], TBool),
  createOp("isThisISOWeek", [TDateArg, TOptions], TBool),
  createOp("isThisMinute", [TDateArg], TBool),
  createOp("isThisMonth", [TDateArg, TOptions], TBool),
  createOp("isThisQuarter", [TDateArg, TOptions], TBool),
  createOp("isThisSecond", [TDateArg], TBool),
  createOp("isThisWeek", [TDateArg, TOptions], TBool),
  createOp("isThisYear", [TDateArg, TOptions], TBool),
  createOp("isThursday", [TDateArg, TOptions], TBool),
  createOp("isToday", [TDateArg, TOptions], TBool),
  createOp("isTomorrow", [TDateArg, TOptions], TBool),
  createOp("isTuesday", [TDateArg, TOptions], TBool),
  createOp("isValid", [TUnknown], TBool),
  createOp("isWednesday", [TDateArg, TOptions], TBool),
  createOp("isWeekend", [TDateArg, TOptions], TBool),
  createOp("isWithinInterval", [TDateArg, TInterval, TOptions], TBool),
  createOp("isYesterday", [TDateArg, TOptions], TBool),
  createOp("lastDayOfDecade", [TDateArg, TOptions], TDate),
  createOp("lastDayOfISOWeek", [TDateArg, TOptions], TDate),
  createOp("lastDayOfISOWeekYear", [TDateArg, TOptions], TDate),
  createOp("lastDayOfMonth", [TDateArg, TOptions], TDate),
  createOp("lastDayOfQuarter", [TDateArg, TOptions], TDate),
  createOp("lastDayOfWeek", [TDateArg, TOptions], TDate),
  createOp("lastDayOfYear", [TDateArg, TOptions], TDate),
  createOp("lightFormat", [TDateArg, TString], TString),
  createOp("max", [TDateArgsArr, TOptions], TDate),
  createOp("milliseconds", [], TNumber),
  createOp("millisecondsToHours", [TNumber], TNumber),
  createOp("millisecondsToMinutes", [TNumber], TNumber),
  createOp("millisecondsToSeconds", [TNumber], TNumber),
  createOp("min", [TDateArgsArr, TOptions], TDate),
  createOp("minutesToHours", [TNumber], TNumber),
  createOp("minutesToMilliseconds", [TNumber], TNumber),
  createOp("minutesToSeconds", [TNumber], TNumber),
  createOp("monthsToQuarters", [TNumber], TNumber),
  createOp("monthsToYears", [TNumber], TNumber),
  createOp("nextDay", [TDateArg, TNumber, TOptions], TDate),
  createOp("nextFriday", [TDateArg, TOptions], TDate),
  createOp("nextMonday", [TDateArg, TOptions], TDate),
  createOp("nextSaturday", [TDateArg, TOptions], TDate),
  createOp("nextSunday", [TDateArg, TOptions], TDate),
  createOp("nextThursday", [TDateArg, TOptions], TDate),
  createOp("nextTuesday", [TDateArg, TOptions], TDate),
  createOp("nextWednesday", [TDateArg, TOptions], TDate),
  createOp("parse", [TString, TString, TDateArg, TOptions], TDate),
  createOp("parseISO", [TString, TOptions], TDate),
  createOp("parseJSON", [TString, TOptions], TDate),
  createOp("previousDay", [TDateArg, TNumber, TOptions], TDate),
  createOp("previousFriday", [TDateArg, TOptions], TDate),
  createOp("previousMonday", [TDateArg, TOptions], TDate),
  createOp("previousSaturday", [TDateArg, TOptions], TDate),
  createOp("previousSunday", [TDateArg, TOptions], TDate),
  createOp("previousThursday", [TDateArg, TOptions], TDate),
  createOp("previousTuesday", [TDateArg, TOptions], TDate),
  createOp("previousWednesday", [TDateArg, TOptions], TDate),
  createOp("quartersToMonths", [TNumber], TNumber),
  createOp("quartersToYears", [TNumber], TNumber),
  createOp("roundToNearestHours", [TDateArg, TOptions], TDate),
  createOp("roundToNearestMinutes", [TDateArg, TOptions], TDate),
  createOp("secondsToHours", [TNumber], TNumber),
  createOp("secondsToMilliseconds", [TNumber], TNumber),
  createOp("secondsToMinutes", [TNumber], TNumber),
  createOp("set", [TDateArg, TDateValues, TOptions], TDate),
  createOp("setDate", [TDateArg, TNumber, TOptions], TDate),
  createOp("setDay", [TDateArg, TNumber, TOptions], TDate),
  createOp("setDayOfYear", [TDateArg, TNumber, TOptions], TDate),
  createOp("setHours", [TDateArg, TNumber, TOptions], TDate),
  createOp("setISODay", [TDateArg, TNumber, TOptions], TDate),
  createOp("setISOWeek", [TDateArg, TNumber, TOptions], TDate),
  createOp("setISOWeekYear", [TDateArg, TNumber, TOptions], TDate),
  createOp("setMilliseconds", [TDateArg, TNumber, TOptions], TDate),
  createOp("setMinutes", [TDateArg, TNumber, TOptions], TDate),
  createOp("setMonth", [TDateArg, TNumber, TOptions], TDate),
  createOp("setQuarter", [TDateArg, TNumber, TOptions], TDate),
  createOp("setSeconds", [TDateArg, TNumber, TOptions], TDate),
  createOp("setWeek", [TDateArg, TNumber, TOptions], TDate),
  createOp("setWeekYear", [TDateArg, TNumber, TOptions], TDate),
  createOp("setYear", [TDateArg, TNumber, TOptions], TDate),
  createOp("startOfDay", [TDateArg, TOptions], TDate),
  createOp("startOfDecade", [TDateArg, TOptions], TDate),
  createOp("startOfHour", [TDateArg, TOptions], TDate),
  createOp("startOfISOWeek", [TDateArg, TOptions], TDate),
  createOp("startOfISOWeekYear", [TDateArg, TOptions], TDate),
  createOp("startOfMinute", [TDateArg, TOptions], TDate),
  createOp("startOfMonth", [TDateArg, TOptions], TDate),
  createOp("startOfQuarter", [TDateArg, TOptions], TDate),
  createOp("startOfSecond", [TDateArg, TOptions], TDate),
  createOp("startOfToday", [TOptions], TDate),
  createOp("startOfTomorrow", [TOptions], TDate),
  createOp("startOfWeek", [TDateArg, TOptions], TDate),
  createOp("startOfWeekYear", [TDateArg, TOptions], TDate),
  createOp("startOfYear", [TDateArg, TOptions], TDate),
  createOp("startOfYesterday", [TOptions], TDate),
  createOp("sub", [TDateArg, TDuration, TOptions], TDate),
  createOp("subBusinessDays", [TDateArg, TNumber, TOptions], TDate),
  createOp("subDays", [TDateArg, TNumber, TOptions], TDate),
  createOp("subHours", [TDateArg, TNumber, TOptions], TDate),
  createOp("subISOWeekYears", [TDateArg, TNumber, TOptions], TDate),
  createOp("subMilliseconds", [TDateArg, TNumber, TOptions], TDate),
  createOp("subMinutes", [TDateArg, TNumber, TOptions], TDate),
  createOp("subMonths", [TDateArg, TNumber, TOptions], TDate),
  createOp("subQuarters", [TDateArg, TNumber, TOptions], TDate),
  createOp("subSeconds", [TDateArg, TNumber, TOptions], TDate),
  createOp("subWeeks", [TDateArg, TNumber, TOptions], TDate),
  createOp("subYears", [TDateArg, TNumber, TOptions], TDate),
  createOp("toDate", [TDateArg, { type: TUnknown, isOptional: true }], TDate),
  createOp("transpose", [TDate, TUnknown], TDate),
  createOp("weeksToDays", [TNumber], TNumber),
  createOp("yearsToDays", [TNumber], TNumber),
  createOp("yearsToMonths", [TNumber], TNumber),
  createOp("yearsToQuarters", [TNumber], TNumber),
];

export const instanceTypes = {};
export default { operations, instanceTypes };
