import { faker } from "@faker-js/faker";
import type { IData, DataType } from "../types";
import type { Context, OperationListItem } from "../execution/types";
import { createDataFromRawValue, getRawValueFromData } from "../utils";
import type { InstanceTypeConfig } from "../packages/registry";

function createFakerOp(
  path: string,
  parameters: OperationListItem["parameters"] = [],
  resultType?: DataType
): OperationListItem {
  const segments = path.split(".");
  return {
    name: path,
    parameters,
    source: { name: "faker" },
    expectedType: resultType,
    handler: (ctx: Context, ...args: IData[]) => {
      const rawArgs = args.map((a) => getRawValueFromData(a, ctx));
      let target: unknown = faker;
      for (const seg of segments.slice(0, -1)) {
        target = (target as Record<string, unknown>)[seg];
      }
      const fn = segments[segments.length - 1];
      let result = (
        (target as Record<string, unknown>)[fn] as (...a: unknown[]) => unknown
      )(...rawArgs);
      if (typeof result === "bigint") result = Number(result);
      return createDataFromRawValue(result, {
        ...ctx,
        expectedType: resultType,
      });
    },
  };
}

const str = { kind: "string" as const };
const num = { kind: "number" as const };
const bool = { kind: "boolean" as const };
const date = {
  kind: "instance" as const,
  className: "Date",
  constructorArgs: [],
};
const undefinedReq = [{ type: { kind: "undefined" as const } }];
const undefinedOpt = [
  { type: { kind: "undefined" as const }, isOptional: true },
];

export const operations: OperationListItem[] = [
  createFakerOp("airline.aircraftType", undefinedOpt, str),
  createFakerOp("airline.airline", undefinedOpt),
  createFakerOp("airline.airplane", undefinedOpt),
  createFakerOp("airline.airport", undefinedOpt),
  createFakerOp("airline.flightNumber", undefinedOpt, str),
  createFakerOp("airline.recordLocator", undefinedOpt, str),
  createFakerOp("airline.seat", undefinedOpt, str),
  createFakerOp("animal.bear", undefinedOpt, str),
  createFakerOp("animal.bird", undefinedOpt, str),
  createFakerOp("animal.cat", undefinedOpt, str),
  createFakerOp("animal.cetacean", undefinedOpt, str),
  createFakerOp("animal.cow", undefinedOpt, str),
  createFakerOp("animal.crocodilia", undefinedOpt, str),
  createFakerOp("animal.dog", undefinedOpt, str),
  createFakerOp("animal.fish", undefinedOpt, str),
  createFakerOp("animal.horse", undefinedOpt, str),
  createFakerOp("animal.insect", undefinedOpt, str),
  createFakerOp("animal.lion", undefinedOpt, str),
  createFakerOp("animal.petName", undefinedOpt, str),
  createFakerOp("animal.rabbit", undefinedOpt, str),
  createFakerOp("animal.rodent", undefinedOpt, str),
  createFakerOp("animal.snake", undefinedOpt, str),
  createFakerOp("animal.type", undefinedOpt, str),
  createFakerOp("book.author", undefinedOpt, str),
  createFakerOp("book.format", undefinedOpt, str),
  createFakerOp("book.genre", undefinedOpt, str),
  createFakerOp("book.publisher", undefinedOpt, str),
  createFakerOp("book.series", undefinedOpt, str),
  createFakerOp("book.title", undefinedOpt, str),
  createFakerOp("color.cmyk", undefinedOpt),
  createFakerOp("color.colorByCSSColorSpace", undefinedOpt),
  createFakerOp("color.cssSupportedFunction", undefinedOpt, str),
  createFakerOp("color.cssSupportedSpace", undefinedOpt, str),
  createFakerOp("color.hsl", undefinedOpt),
  createFakerOp("color.human", undefinedOpt, str),
  createFakerOp("color.hwb", undefinedOpt),
  createFakerOp("color.lab", undefinedOpt),
  createFakerOp("color.lch", undefinedOpt),
  createFakerOp("color.rgb", undefinedOpt, str),
  createFakerOp("color.space", undefinedOpt, str),
  createFakerOp("commerce.department", undefinedOpt, str),
  createFakerOp("commerce.isbn", undefinedOpt, str),
  createFakerOp("commerce.price", undefinedOpt, str),
  createFakerOp("commerce.product", undefinedOpt, str),
  createFakerOp("commerce.productAdjective", undefinedOpt, str),
  createFakerOp("commerce.productDescription", undefinedOpt, str),
  createFakerOp("commerce.productMaterial", undefinedOpt, str),
  createFakerOp("commerce.productName", undefinedOpt, str),
  createFakerOp("commerce.upc", undefinedOpt, str),
  createFakerOp("company.buzzAdjective", undefinedOpt, str),
  createFakerOp("company.buzzNoun", undefinedOpt, str),
  createFakerOp("company.buzzPhrase", undefinedOpt, str),
  createFakerOp("company.buzzVerb", undefinedOpt, str),
  createFakerOp("company.catchPhrase", undefinedOpt, str),
  createFakerOp("company.catchPhraseAdjective", undefinedOpt, str),
  createFakerOp("company.catchPhraseDescriptor", undefinedOpt, str),
  createFakerOp("company.catchPhraseNoun", undefinedOpt, str),
  createFakerOp("company.name", undefinedOpt, str),
  createFakerOp("database.collation", undefinedOpt, str),
  createFakerOp("database.column", undefinedOpt, str),
  createFakerOp("database.engine", undefinedOpt, str),
  createFakerOp("database.mongodbObjectId", undefinedOpt, str),
  createFakerOp("database.type", undefinedOpt, str),
  createFakerOp("datatype.boolean", undefinedOpt, bool),
  createFakerOp("date.anytime", undefinedOpt, date),
  createFakerOp("date.between", undefinedReq),
  createFakerOp("date.betweens", undefinedReq),
  createFakerOp("date.birthdate", undefinedOpt, date),
  createFakerOp("date.future", undefinedOpt, date),
  createFakerOp("date.month", undefinedOpt, str),
  createFakerOp("date.past", undefinedOpt, date),
  createFakerOp("date.recent", undefinedOpt, date),
  createFakerOp("date.soon", undefinedOpt, date),
  createFakerOp("date.timeZone", undefinedOpt, str),
  createFakerOp("date.weekday", undefinedOpt, str),
  createFakerOp("finance.accountName", undefinedOpt, str),
  createFakerOp("finance.accountNumber", undefinedOpt, str),
  createFakerOp("finance.amount", undefinedOpt, str),
  createFakerOp("finance.bic", undefinedOpt, str),
  createFakerOp("finance.bitcoinAddress", undefinedOpt, str),
  createFakerOp("finance.creditCardCVV", undefinedOpt, str),
  createFakerOp("finance.creditCardIssuer", undefinedOpt, str),
  createFakerOp("finance.creditCardNumber", undefinedOpt, str),
  createFakerOp("finance.currency", undefinedOpt),
  createFakerOp("finance.currencyCode", undefinedOpt, str),
  createFakerOp("finance.currencyName", undefinedOpt, str),
  createFakerOp("finance.currencyNumericCode", undefinedOpt, str),
  createFakerOp("finance.currencySymbol", undefinedOpt, str),
  createFakerOp("finance.ethereumAddress", undefinedOpt, str),
  createFakerOp("finance.iban", undefinedOpt, str),
  createFakerOp("finance.litecoinAddress", undefinedOpt, str),
  createFakerOp("finance.pin", undefinedOpt, str),
  createFakerOp("finance.routingNumber", undefinedOpt, str),
  createFakerOp("finance.transactionDescription", undefinedOpt, str),
  createFakerOp("finance.transactionType", undefinedOpt, str),
  createFakerOp("food.adjective", undefinedOpt, str),
  createFakerOp("food.description", undefinedOpt, str),
  createFakerOp("food.dish", undefinedOpt, str),
  createFakerOp("food.ethnicCategory", undefinedOpt, str),
  createFakerOp("food.fruit", undefinedOpt, str),
  createFakerOp("food.ingredient", undefinedOpt, str),
  createFakerOp("food.meat", undefinedOpt, str),
  createFakerOp("food.spice", undefinedOpt, str),
  createFakerOp("food.vegetable", undefinedOpt, str),
  createFakerOp("git.branch", undefinedOpt, str),
  createFakerOp("git.commitDate", undefinedOpt, str),
  createFakerOp("git.commitEntry", undefinedOpt, str),
  createFakerOp("git.commitMessage", undefinedOpt, str),
  createFakerOp("git.commitSha", undefinedOpt, str),
  createFakerOp("hacker.abbreviation", undefinedOpt, str),
  createFakerOp("hacker.adjective", undefinedOpt, str),
  createFakerOp("hacker.ingverb", undefinedOpt, str),
  createFakerOp("hacker.noun", undefinedOpt, str),
  createFakerOp("hacker.phrase", undefinedOpt, str),
  createFakerOp("hacker.verb", undefinedOpt, str),
  createFakerOp("helpers.arrayElement", undefinedReq),
  createFakerOp("helpers.arrayElements", undefinedReq),
  createFakerOp("helpers.enumValue", undefinedReq),
  createFakerOp("helpers.fake", undefinedReq),
  createFakerOp("helpers.fromRegExp", undefinedReq, str),
  createFakerOp("helpers.maybe", undefinedReq),
  createFakerOp("helpers.multiple", undefinedOpt),
  createFakerOp("helpers.mustache", undefinedOpt, str),
  createFakerOp("helpers.objectEntry", undefinedReq),
  createFakerOp("helpers.objectKey", undefinedReq),
  createFakerOp("helpers.objectValue", undefinedReq),
  createFakerOp("helpers.rangeToNumber", undefinedReq, num),
  createFakerOp("helpers.replaceCreditCardSymbols", undefinedOpt, str),
  createFakerOp("helpers.replaceSymbols", undefinedOpt, str),
  createFakerOp("helpers.shuffle", undefinedReq),
  createFakerOp("helpers.slugify", undefinedOpt, str),
  createFakerOp("helpers.uniqueArray", undefinedOpt),
  createFakerOp("helpers.weightedArrayElement", undefinedReq),
  createFakerOp("image.avatar", undefinedOpt, str),
  createFakerOp("image.avatarGitHub", undefinedOpt, str),
  createFakerOp("image.dataUri", undefinedOpt, str),
  createFakerOp("image.personPortrait", undefinedOpt, str),
  createFakerOp("image.url", undefinedOpt, str),
  createFakerOp("image.urlLoremFlickr", undefinedOpt, str),
  createFakerOp("image.urlPicsumPhotos", undefinedOpt, str),
  createFakerOp("internet.displayName", undefinedOpt, str),
  createFakerOp("internet.domainName", undefinedOpt, str),
  createFakerOp("internet.domainSuffix", undefinedOpt, str),
  createFakerOp("internet.domainWord", undefinedOpt, str),
  createFakerOp("internet.email", undefinedOpt, str),
  createFakerOp("internet.emoji", undefinedOpt, str),
  createFakerOp("internet.exampleEmail", undefinedOpt, str),
  createFakerOp("internet.httpMethod", undefinedOpt, str),
  createFakerOp("internet.httpStatusCode", undefinedOpt, num),
  createFakerOp("internet.ip", undefinedOpt, str),
  createFakerOp("internet.ipv4", undefinedOpt, str),
  createFakerOp("internet.ipv6", undefinedOpt, str),
  createFakerOp("internet.jwt", undefinedOpt, str),
  createFakerOp("internet.jwtAlgorithm", undefinedOpt, str),
  createFakerOp("internet.mac", undefinedOpt, str),
  createFakerOp("internet.password", undefinedOpt, str),
  createFakerOp("internet.port", undefinedOpt, num),
  createFakerOp("internet.protocol", undefinedOpt, str),
  createFakerOp("internet.url", undefinedOpt, str),
  createFakerOp("internet.userAgent", undefinedOpt, str),
  createFakerOp("internet.username", undefinedOpt, str),
  createFakerOp("location.buildingNumber", undefinedOpt, str),
  createFakerOp("location.cardinalDirection", undefinedOpt, str),
  createFakerOp("location.city", undefinedOpt, str),
  createFakerOp("location.continent", undefinedOpt, str),
  createFakerOp("location.country", undefinedOpt, str),
  createFakerOp("location.countryCode", undefinedOpt, str),
  createFakerOp("location.county", undefinedOpt, str),
  createFakerOp("location.direction", undefinedOpt, str),
  createFakerOp("location.language", undefinedOpt),
  createFakerOp("location.latitude", undefinedOpt, num),
  createFakerOp("location.longitude", undefinedOpt, num),
  createFakerOp("location.nearbyGPSCoordinate", undefinedOpt),
  createFakerOp("location.ordinalDirection", undefinedOpt, str),
  createFakerOp("location.secondaryAddress", undefinedOpt, str),
  createFakerOp("location.state", undefinedOpt, str),
  createFakerOp("location.street", undefinedOpt, str),
  createFakerOp("location.streetAddress", undefinedOpt, str),
  createFakerOp("location.timeZone", undefinedOpt, str),
  createFakerOp("location.zipCode", undefinedOpt, str),
  createFakerOp("lorem.lines", undefinedOpt, str),
  createFakerOp("lorem.paragraph", undefinedOpt, str),
  createFakerOp("lorem.paragraphs", undefinedOpt, str),
  createFakerOp("lorem.sentence", undefinedOpt, str),
  createFakerOp("lorem.sentences", undefinedOpt, str),
  createFakerOp("lorem.slug", undefinedOpt, str),
  createFakerOp("lorem.text", undefinedOpt, str),
  createFakerOp("lorem.word", undefinedOpt, str),
  createFakerOp("lorem.words", undefinedOpt, str),
  createFakerOp("music.album", undefinedOpt, str),
  createFakerOp("music.artist", undefinedOpt, str),
  createFakerOp("music.genre", undefinedOpt, str),
  createFakerOp("music.songName", undefinedOpt, str),
  createFakerOp("number.bigInt", undefinedOpt, num),
  createFakerOp("number.binary", undefinedOpt, str),
  createFakerOp("number.float", undefinedOpt, num),
  createFakerOp("number.hex", undefinedOpt, str),
  createFakerOp("number.int", undefinedOpt, num),
  createFakerOp("number.octal", undefinedOpt, str),
  createFakerOp("number.romanNumeral", undefinedOpt, str),
  createFakerOp("person.bio", undefinedOpt, str),
  createFakerOp("person.firstName", undefinedOpt, str),
  createFakerOp("person.fullName", undefinedOpt, str),
  createFakerOp("person.gender", undefinedOpt, str),
  createFakerOp("person.jobArea", undefinedOpt, str),
  createFakerOp("person.jobDescriptor", undefinedOpt, str),
  createFakerOp("person.jobTitle", undefinedOpt, str),
  createFakerOp("person.jobType", undefinedOpt, str),
  createFakerOp("person.lastName", undefinedOpt, str),
  createFakerOp("person.middleName", undefinedOpt, str),
  createFakerOp("person.prefix", undefinedOpt, str),
  createFakerOp("person.sex", undefinedOpt, str),
  createFakerOp("person.sexType", undefinedOpt, str),
  createFakerOp("person.suffix", undefinedOpt, str),
  createFakerOp("person.zodiacSign", undefinedOpt, str),
  createFakerOp("phone.imei", undefinedOpt, str),
  createFakerOp("phone.number", undefinedOpt, str),
  createFakerOp("science.chemicalElement", undefinedOpt),
  createFakerOp("science.unit", undefinedOpt),
  createFakerOp("string.alpha", undefinedOpt, str),
  createFakerOp("string.alphanumeric", undefinedOpt, str),
  createFakerOp("string.binary", undefinedOpt, str),
  createFakerOp("string.fromCharacters", undefinedOpt, str),
  createFakerOp("string.hexadecimal", undefinedOpt, str),
  createFakerOp("string.nanoid", undefinedOpt, str),
  createFakerOp("string.numeric", undefinedOpt, str),
  createFakerOp("string.octal", undefinedOpt, str),
  createFakerOp("string.sample", undefinedOpt, str),
  createFakerOp("string.symbol", undefinedOpt, str),
  createFakerOp("string.ulid", undefinedOpt, str),
  createFakerOp("string.uuid", undefinedOpt, str),
  createFakerOp("system.commonFileExt", undefinedOpt, str),
  createFakerOp("system.commonFileName", undefinedOpt, str),
  createFakerOp("system.commonFileType", undefinedOpt, str),
  createFakerOp("system.cron", undefinedOpt, str),
  createFakerOp("system.directoryPath", undefinedOpt, str),
  createFakerOp("system.fileExt", undefinedOpt, str),
  createFakerOp("system.fileName", undefinedOpt, str),
  createFakerOp("system.filePath", undefinedOpt, str),
  createFakerOp("system.fileType", undefinedOpt, str),
  createFakerOp("system.mimeType", undefinedOpt, str),
  createFakerOp("system.networkInterface", undefinedOpt, str),
  createFakerOp("system.semver", undefinedOpt, str),
  createFakerOp("vehicle.bicycle", undefinedOpt, str),
  createFakerOp("vehicle.color", undefinedOpt, str),
  createFakerOp("vehicle.fuel", undefinedOpt, str),
  createFakerOp("vehicle.manufacturer", undefinedOpt, str),
  createFakerOp("vehicle.model", undefinedOpt, str),
  createFakerOp("vehicle.type", undefinedOpt, str),
  createFakerOp("vehicle.vehicle", undefinedOpt, str),
  createFakerOp("vehicle.vin", undefinedOpt, str),
  createFakerOp("vehicle.vrm", undefinedOpt, str),
  createFakerOp("word.adjective", undefinedOpt, str),
  createFakerOp("word.adverb", undefinedOpt, str),
  createFakerOp("word.conjunction", undefinedOpt, str),
  createFakerOp("word.interjection", undefinedOpt, str),
  createFakerOp("word.noun", undefinedOpt, str),
  createFakerOp("word.preposition", undefinedOpt, str),
  createFakerOp("word.sample", undefinedOpt, str),
  createFakerOp("word.verb", undefinedOpt, str),
  createFakerOp("word.words", undefinedOpt, str),
];

export const instanceTypes: Record<string, InstanceTypeConfig> = {};

export default { operations, instanceTypes };
